<?php
// $Id$

/**
 * @file
 * Sweaver functions.
 */

/**
 * Default paths to exclude the frontend editor from.
 */
define('SWEAVER_PATHS_EXCLUDE', "admin*\nnode/add*\nnode/*/edit\nuser/*/edit\nbatch*");

/**
 * Default selectors to exclude from selecting.
 */
define('SWEAVER_SELECTORS_EXCLUDE', "#sweaver-frontend\n#admin-menu\n.colorpicker\n#sweaver-messages\n#sweaver-popup\n#follow-link");

/**
 * Default classes to exclude from not being themed.
 */
define('SWEAVER_CLASSES_EXCLUDE', "clear\nclear-fix\nclearfix\nsweaver\nsweaver-hovered\nsweaver-clicked\nsweaver-clicked-temp");

/**
 * Default skin.
 */
define('SWEAVER_SKIN', "default");

/**
 * Implements hook_permission().
 */
function sweaver_permission() {
  return array(
    'configure sweaver' => array(
      'title' => t('Configure the editor, selectors, properties, types and other plugins.')
    ),
    'use editor' => array(
      'title' => t('Use the front end editor.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sweaver_menu() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_menu();
}

/**
 * Implements hook_theme().
 */
function sweaver_theme() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_theme();
}

/**
 * Implements hook_ctools_plugin_api().
 */
function sweaver_ctools_plugin_api($owner, $api) {
  if ($owner == 'sweaver' && ($api == 'sweaver' || $api == 'plugins')) {
    return array('version' => 1);
  }
}

/**
 * Implements hook_ctools_plugin_plugins().
 */
function sweaver_ctools_plugin_plugins() {
  return array(
    'cache' => TRUE,
    'use hooks' => TRUE,
  );
}

/**
 * Implements hook_default_sweaver_selector().
 */
function sweaver_default_sweaver_selector() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_default_sweaver_selector();
}

/**
 * Implements hook_default_sweaver_property().
 */
function sweaver_default_sweaver_property() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_default_sweaver_property();
}

/**
 * Implements hook_default_sweaver_type().
 */
function sweaver_default_sweaver_type() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_default_sweaver_type();
}

/**
 * Implements hook_sweaver_plugins().
 */
function sweaver_sweaver_plugins() {
  module_load_include('inc', 'sweaver', 'sweaver.registry');
  return _sweaver_sweaver_plugins();
}

/**
 * CTools selectors list callback for bulk export.
 */
function sweaver_ctools_selectors_list() {
  return sweaver_ctools_object_list('selector');
}

/**
 * CTools properties list callback for bulk export.
 */
function sweaver_ctools_properties_list() {
  return sweaver_ctools_object_list('property');
}

/**
 * CTools types list callback for bulk export.
 */
function sweaver_ctools_types_list() {
  return sweaver_ctools_object_list('type');
}

/**
 * Helper function to return list for CTools.
 */
function sweaver_ctools_object_list($object_type, $export_type = 2, $parent_check = FALSE) {
  $list = array();
  $objects = sweaver_object_load(NULL, $object_type, 'enabled');
  foreach ($objects as $object) {
    if ($object->export_type != $export_type) {

      // Parent check.
      if ($parent_check) {
        if ($object->property_type == 'parent') {
          continue;
        }
        elseif (!empty($object->property_parent)) {
          $object->description = $objects[$object->property_parent]->description .': '. $object->description;
        }
      }
      $list[$object->name] = $object->description;
    }
  }
  return $list;
}

/**
 * CTools selector export function.
 */
function sweaver_export_sweaver_selector($object) {
  return sweaver_export_sweaver_object($object, 'selector');
}

/**
 * CTools property export function.
 */
function sweaver_export_sweaver_property($object) {
  return sweaver_export_sweaver_object($object, 'property');
}

/**
 * CTools property export function.
 */
function sweaver_export_sweaver_type($object) {
  return sweaver_export_sweaver_object($object, 'type');
}

/**
 * CTools object export function.
 */
function sweaver_export_sweaver_object($object, $object_type) {
  ctools_include('export');
  sweaver_export_check_serialized_keys($object);
  $output = ctools_export_object('sweaver_' . $object_type, $object, '  ');
  return $output;
}

/**
 * Check if we have a serialized key. If so convert it to an array.
 *
 * @param $object
 *   A sweaver object.
 */
function sweaver_export_check_serialized_keys($object) {
  if (isset($object->table)) {
    $object_type = str_replace('sweaver_', '', $object->table);
    $key = $object_type . '_options';
    if (isset($object->{$key}) && !empty($object->{$key}) && is_string($object->{$key})) {
      $object->{$key} = unserialize($object->{$key});
    }
  }
}

/**
 * Load one object or all objects.
 *
 * @param $name
 *   The machine name of the object.
 * @param $map
 *   Can be an array passed on by the load arguments of the menu or a string.
 *   In case of array, object_type will be index 6.
 * @param $status
 *   Whether to return all objects or only enabled.
 * @return
 *   One object or an array of objects.
 */
function sweaver_object_load($name = NULL, $map = NULL, $status = 'enabled') {

  static $run = FALSE;
  static $objects = NULL;
  $object_type = is_array($map) ? $map[6] : $map;

  if (!$run) {

    if ($objects_cache = cache_get('sweaver')) {
      $objects = $objects_cache->data;
    }
    else {
      ctools_include('export');
      $objects = new stdClass;
      foreach (array('sweaver_selector', 'sweaver_property', 'sweaver_type') as $object_to_load) {
        $loaded_objects = ctools_export_load_object($object_to_load);
        foreach ($loaded_objects as $key => $object) {
          $object_type_key = str_replace('sweaver_', '', $object->table);
          if (!isset($object->disabled) || (isset($object->disabled) && $object->disabled == FALSE)) {
            $objects->{$object_type_key}->enabled[$key] = $object;
          }
          $objects->{$object_type_key}->all[$key] = $object;
        }
      }

      // Let sweaver plugins alter objects.
      foreach (sweaver_get_plugin(NULL, TRUE) as $plugin) {
        $plugin_name = $plugin['name'];
        $object = sweaver_get_plugin($plugin_name);
        $object->sweaver_objects_alter($objects);
      }

      cache_set('sweaver', $objects);
    }
    $run = TRUE;
  }

  if ($name) {
    return isset($objects->{$object_type}->all[$name]) ? $objects->{$object_type}->all[$name] : FALSE;
  }
  else {
    return isset($objects->{$object_type}->{$status}) ? $objects->{$object_type}->{$status} : array();
  }
}

/**
 * Get all plugins or a plugin handler.
 *
 * @param $plugin_name
 *   The name of the plugin.
 * @param $enabled
 *   Whether the plugin has to be enabled or not.
 * @return
 *   Either a list of (enabled) plugins or a(n) (enabled) loaded plugin class.
 */
function sweaver_get_plugin($plugin_name = NULL, $enabled = NULL) {
  static $run = FALSE;
  static $cache, $cached_plugins, $cached_plugins_enabled = array();

  if (!$run) {
    ctools_include('plugins');
    if ($plugins_cache = cache_get('sweaver_plugins')) {
      $cached_plugins = $plugins_cache->data['sweaver_plugins'];
      $cached_plugins_enabled = $plugins_cache->data['sweaver_plugins_enabled'];
    }
    else {
      $plugins = ctools_get_plugins('sweaver', 'plugins');
      $cached_plugins = $plugins;

      // Build enabled plugins.
      foreach ($cached_plugins as $key => $plugin) {
        if (variable_get('sweaver_plugin_status_' . $key, FALSE)) {
          $cached_plugins_enabled[$key] = $plugin;
        }
      }

      // Cache the plugins ourselves too.
      $sweaver_plugins['sweaver_plugins'] = $cached_plugins;
      $sweaver_plugins['sweaver_plugins_enabled'] = $cached_plugins_enabled;
      cache_set('sweaver_plugins', $sweaver_plugins);
    }
    $run = TRUE;
  }

  if ($plugin_name == NULL) {
    return ($enabled) ? $cached_plugins_enabled : $cached_plugins;
  }
  else {
    if (!isset($cache[$plugin_name])) {
      $check = ($enabled) ? isset($cached_plugins_enabled[$plugin_name]) : TRUE;
      if ($check && $class = ctools_plugin_get_class($cached_plugins[$plugin_name], 'handler')) {
        $cache[$plugin_name] = new $class($cached_plugins[$plugin_name]);
      }
      else {
        $cache[$plugin_name] = FALSE;
      }
    }
    return isset($cache[$plugin_name]) ? $cache[$plugin_name] : FALSE;
  }
}

/**
 * Implements hook_init().
 */
function sweaver_init() {
  // We use the drupal_static here instead of a session, because
  // pressflow doesn't allow us to start a session without breaking
  // the page cache.
  $load_style = &drupal_static('load_style', TRUE);
  if (sweaver_show_editor()) {
    $load_style = FALSE;
    $inline_js_settings = array('sweaver' => array('invokes' => array()));

    foreach (sweaver_get_plugin(NULL, TRUE) as $plugin) {
      $plugin_name = $plugin['name'];
      $object = sweaver_get_plugin($plugin_name);
      // Fire init.
      $object->sweaver_init();
      // CSS and JS.
      $object->sweaver_form_css_js($inline_js_settings);
    }

    // JS inline settings.
    drupal_add_js($inline_js_settings, 'setting');
  }

  // Add stylesheet if necessary
  // @todo check if we need hook_css_alter ? or maybe move to page_alter ?
  if (variable_get('sweaver_load_style_when_editor_inactive', TRUE) || sweaver_show_editor()) {
    global $theme_key;
    $sweaver = sweaver_get_plugin('sweaver_plugin');
    $sweaver_style = $sweaver->sweaver_get_current_style($theme_key);
    if (isset($sweaver_style->css) && drupal_static('load_style')) {
      $css_path = file_default_scheme() . '://sweaver/sweaver_' . $theme_key . '_' . $sweaver_style->style_id . '_' . $sweaver_style->type . ' .css';
      $settings = array(
        'weight' => 1000,
        'preprocess' => TRUE,
      );
      drupal_add_css($css_path, $settings);
    }
  }
}

/**
 * Implements hook_page_alter().
 */
function sweaver_page_alter(&$page) {
  // We return the complete form in the page_bottom.
  if (sweaver_show_editor()) {
    $page['page_bottom']['sweaver'] = array(
      '#markup' => drupal_render(drupal_get_form('sweaver_frontend')) . '<div id="sweaver-messages"><div class="close">x</div><div class="message"></div></div>',
    );
  }
}

/**
 * Function to check if we are going to show the editor.
 */
function sweaver_show_editor() {
  static $run = FALSE;
  static $return = FALSE;

  if (!$run) {
    $run = TRUE;

    // Let's do the check for the editor early.
    if (variable_get('sweaver_enabled', TRUE)) {
      // Path visibility.
      $path = drupal_get_path_alias($_GET['q']);
      $page_match = drupal_match_path($path, variable_get('sweaver_paths', SWEAVER_PATHS_EXCLUDE));
      if ($path != $_GET['q']) {
        $page_match = $page_match || drupal_match_path($_GET['q'], variable_get('sweaver_paths', SWEAVER_PATHS_EXCLUDE));
      }
      $page_match = !(0 xor $page_match);

      // Compare all variables.
      if (user_access('use editor') && $page_match) {
        $return = TRUE;
      }
    }
  }
  return $return;
}

/**
 * Rock 'n' roll: the sweaver editor.
 */
function sweaver_frontend(&$form_state) {
  $form = array();
  $weight = 1;
  global $theme_key;
  $form['#plugins'] = array();
  $form['#theme'] = 'sweaver_plugin';
  $form['#attributes'] = array('enctype' => 'multipart/form-data');
  $plugins_order = variable_get('sweaver_plugins_weight', array());

  foreach (sweaver_get_plugin(NULL, TRUE) as $plugin) {
    $plugin_name = $plugin['name'];
    $object = sweaver_get_plugin($plugin_name);

    // Calculate weight.
    $default_weight = isset($plugins_order[$plugin_name]) ? $plugins_order[$plugin_name] : $weight++;
    if ($plugin_name == 'sweaver_plugin') $default_weight = -100;
    $form['#plugins_order'][$plugin_name] = $default_weight;
    $form['#plugins_full'][$plugin_name] = $plugin;

    // Form.
    $plugin_form = $object->sweaver_form();
    if (!empty($plugin_form)) {
      $form[$plugin['name']]['form'] = $plugin_form;
      if (isset($plugin['handler']['tab'])) {
        $form[$plugin['name']]['#tab_name'] = isset($plugin['handler']['tab']) ? $plugin['handler']['tab'] : drupal_ucfirst($plugin_name);
        $form[$plugin['name']]['#tab_description'] = isset($plugin['handler']['tab_description']) ? $plugin['handler']['tab_description'] : '';
      }
    }
  }

  // Editor messages.
  $messages = $object->sweaver_session();
  $object->sweaver_session(NULL, 'sweaver_editor_messages', TRUE);
  $form['sweaver-editor-messages'] = array(
    '#type' => 'hidden',
    '#value' => trim($messages),
  );

  $form['#current_theme'] = $theme_key;
  $form['destination'] = array(
    '#type' => 'hidden',
    '#value' => $_GET['q'],
  );

  return $form;
}

/**
 * Sweaver frontend submit.
 */
function sweaver_frontend_submit($form, &$form_state) {

  foreach (sweaver_get_plugin(NULL, TRUE) as $plugin) {
    $plugin_name = $plugin['name'];
    $object = sweaver_get_plugin($plugin_name);
    // In the first version, we'll let everyone who has submit methods
    // simply do their stuff with the submitted values.
    $object->sweaver_form_submit($form, $form_state);
  }

  // Redirect to same path. We issue this function so things like
  // session, current style and possible others are properly set.
  drupal_goto();
}

/**
 * Sweaver menu callback.
 *
 * @param $settings
 *   A collection of page arguments from the menu callback.
 * @return
 *   The rendered page - can be form or anything else.
 */
function sweaver_menu_callback($settings) {
  $plugin_name = $settings['plugin'];
  $callback_method = (isset($settings['callback_method'])) ? $settings['callback_method']: 'sweaver_menu_callback';
  $return_method = (isset($settings['return_method'])) ? $settings['return_method'] : 'drupal_get_form';
  $js = (isset($settings['js'])) ? TRUE : FALSE;

  if ($object = sweaver_get_plugin($plugin_name, TRUE)) {
    $output = $object->$callback_method();
    if (!empty($output)) {
      if ($return_method == 'drupal_get_form') {
        return drupal_get_form('sweaver_menu_callback_form', $output, $plugin_name, $callback_method);
      }
      elseif (isset($js)) {
        exit(drupal_to_js($output));
      }
      elseif (!empty($return_method) && function_exists($return_method)) {
        return $return_method($output);
      }
      else {
        return $output;
      }
    }
  }

  return t('No page found or you do not have sufficient permissions to access the page.');
}

/**
 * Helper function to return the form passed by sweaver_menu_callback.
 *
 * @param $plugin_name
 *   Name of the plugin.
 * @param $callback_method
 *   Name of the method to call.
 * @return $form
 *   The rendered form.
 */
function sweaver_menu_callback_form($form, &$form_state, $current_form, $plugin_name, $callback_method) {
  $form = $current_form;
  $form['#plugin_name'] = $plugin_name;
  $form['#callback_method'] = $callback_method;
  return $form;
}

/**
 * Sweaver menu callback validate.
 */
function sweaver_menu_callback_form_validate($form, &$form_state) {
  $object = sweaver_get_plugin($form['#plugin_name']);
  $callback_validate_function = $form['#callback_method'] . '_validate';
  if (method_exists($object, $callback_validate_function)) {
    $object->$callback_validate_function($form, $form_state);
  }
}

/**
 * Sweaver menu callback form submit.
 */
function sweaver_menu_callback_form_submit($form, &$form_state) {
  $object = sweaver_get_plugin($form['#plugin_name']);
  $callback_submit_function = $form['#callback_method'] . '_submit';
  if (method_exists($object, $callback_submit_function)) {
    $object->$callback_submit_function($form, $form_state);
  }
}

/**
 * Implements custom_theme().
 */
function sweaver_custom_theme() {
  $sweaver = sweaver_get_plugin('sweaver_plugin');
  if ($theme_switch = $sweaver->sweaver_session(NULL, 'sweaver_plugin_switch_theme')) {
    return $sweaver->sweaver_session(NULL, 'sweaver_plugin_switch_theme');
  }
}
